Side nav bar now covers entire screen on mobile devices. Exit button …
tedx-uofw/tedxuofw-website pull request #13
Opened 2024-10-31 01:06 UTC by rushil-arun

Changed the width of the side nav bar on mobile devices to fit the entire screen.

2024-10-31 01:07 UTC, rushil-arun commented
For Issues #8

2024-11-10 22:25 UTC, ndaeila requested changes
Please see review. Thank you!

2024-11-10 22:25 UTC, ndaeila commented on src/components/navbar/navbar.css
>    #half-bg-side {
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/3c96a683-0e08-4ae4-bc37-04804c518f8e">
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/2fb65e8e-bc6d-4993-9025-ebf2d054ab22">


For a wider view, like on an iPad or something, can you keep the half-panel, and only show the full-panel for Mobile where it makes sense? Maybe use the sm breakpoint?

Or you can have the panel cover the entire screen as you have, but fix everything to the top right of the screen so it always looks like the contents of the nav bar are right-aligned.

2024-11-12 03:29 UTC, rushil-arun commented
I adjusted to the side for ipad, but I'm not sure I did it properly dynamically.

2024-11-14 22:49 UTC, sais14 reviewed
On mobile view, it still looks like the menu is right-aligned rather than centered.  The ipad/regular web sizes looks right, as it does look like its taking up the entire screen but right aligned.
![image](https://github.com/user-attachments/assets/9d8d17b6-fdc7-441d-b3a3-4ba4f209fd78)

2024-11-14 23:34 UTC, rushil-arun commented
@sais14 I think the side nav should always be right aligned; did you mean that it looks centered on mobile?

Thanks for the review!

2024-11-14 23:35 UTC, ndaeila commented
> @sais14 I think the side nav should always be right aligned; did you mean that it looks centered on mobile?
> 
> Thanks for the review!

This can wait for the meeting - I want to talk about it in person.

2024-11-14 23:37 UTC, rushil-arun commented
Sounds good

2024-11-23 02:45 UTC, closed without merging

2024-11-23 02:46 UTC, rushil-arun commented
Moved progress onto new branch (Current Side Nav Bar...). Check for PR from that branch.