Fixed arrow button, working click and scroll
tedx-uofw/tedxuofw-website pull request #14
Opened 2024-10-31 01:48 UTC by timmh7

1. Added hover effect so the arrow button in landing page is more interactive
2. Added functioning scroll after arrow button is pressed

2024-11-08 21:43 UTC, timmh7 commented
Updated down arrow to now have a vertical moving animation

2024-11-10 22:05 UTC, ndaeila requested changes
That's all that I think needs changing. Everything else is good.

2024-11-10 22:05 UTC, ndaeila commented on src/components/landing.css
Can you make the down-arrow-container bigger? It's the same size as the down-arrow currently, which is a small container to press. Making it bigger may make things easier.

2024-11-14 22:14 UTC, ndaeila approved these changes

2024-11-14 22:23 UTC, merged